[package]
name = "snoop"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
default = ["reader", "writer"] #todo
reader = []
writer = []

[profile.profiling]
inherits = "release"
debug = true
