# name: release

# on:
#   push:
#     branches: [master]
#     tags:
#       - "v*"
# permissions:
#   contents: read

# env:
#   project: snoop

# jobs:
#   build:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         include:
#           - target: x86_64-unknown-linux-gnu
#             os: ubuntu-latest
#           - target: armv7-unknown-linux-gnueabihf
#             os: ubuntu-latest
#           - target: x86_64-apple-darwin
#             os: macos-latest
#           - target: x86_64-pc-windows-msvc
#             os: windows-latest

#     steps:
#       - uses: actions/checkout@v4
#        - uses: dtolnay/rust-toolchain@master

#       - uses: Swatinem/rust-cache@v1

#       - name: Build
#         uses: actions-rs/cargo@v1
#         with:
#           use-cross: true
#           command: build
#           args: --release --locked --target=${{ matrix.target }}

#       - name: Upload
#         if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
#         uses: actions/upload-artifact@v2
#         with:
#           name: ${{ env.project }}_${{ matrix.target }}
#           path: |
#             ./target/${{ matrix.target }}/release/${{ env.project }}
#             ./target/${{ matrix.target }}/release/${{ env.project }}.exe
#   release:
#     if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
#     needs: [build]
#     runs-on: ubuntu-latest
#     steps:
#       - name: Download
#         uses: actions/download-artifact@v2
#         with:
#           path: artifacts

#       - name: Archives
#         run: find artifacts -mindepth 1 -maxdepth 1  -exec tar -C {} -cvzf {}.tgz . \;

#       - name: Release
#         uses: softprops/action-gh-release@v1
#         with:
#           files: |
#             artifacts/*.tgz
#         env:
#           GITHUB_TOKEN: ${{ secrets.PAT }}